spring.application.name=super-admin

spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_platform
spring.datasource.username=postgres
spring.datasource.password=ROOT

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=dev

logging.level.com.enterprise.superadmin.platform_branding_service=DEBUG
logging.file.name=logs/super-admin.log