spring.application.name=super-admin

spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_platform
spring.datasource.username=postgres
spring.datasource.password=Niranjan@45

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
