spring.application.name=super-admin

spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_platform
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
